apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-postgresql
data:
  DB_HOST: "10.100.249.234"
  DB_PORT: "5432"
  DB_USERNAME: "admin"
  DB_NAME: "brdatabase"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  DB_PASSWORD: YWRtaW4=